image: ubuntu:18.04
stages:
  - test
  - triggers
  - publish

.common: &common |
   sed -i 's|deb http://deb-repo.oxfordnanolabs.local/apt|#deb http://deb-repo.oxfordnanolabs.local/apt|g' /etc/apt/sources.list /etc/apt/sources.list.d/*.list || true
   apt-get clean
   apt-get update
   apt-get install -y curl git wget lsb-release gnupg build-essential openssl
   wget -O- http://deb-repo.oxfordnanolabs.local/apt/roger.pettett@nanoporetech.com.key | apt-key add -
   echo "deb http://deb-repo.oxfordnanolabs.local/apt $(lsb_release -cs) non-free" > /etc/apt/sources.list.d/deb-repo.list
   curl -sL https://deb.nodesource.com/setup_12.x > nodejs-repo
   chmod +x nodejs-repo
   ./nodejs-repo
   rm nodejs-repo
   make deps

test:
  stage: test
  script:
    - *common
    - make cover
  variables:
    PATCH: $CI_BUILD_ID

release:
  stage: publish
  script:
    - *common
    - jq ".version=\"$(echo $CI_COMMIT_TAG | sed 's/release-//g')\"" < package.json > package.json.tmp && mv package.json.tmp package.json
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    - npm publish --access=public
  only:
    - /^release-\d+\.\d+(?:.\d+)?(?:-\S+)?$/ # use regexp
  only:
    - tags

pages:
  stage: triggers
  allow_failure: true
  script:
    - *common
    - mkdir -p public
    - (make cover | tee coverage.txt) && mv coverage/* public/
    - (echo -n "Coverage "; grep "All files" coverage.txt | awk '{print $6}')
    - rm coverage.txt
  coverage: '/Coverage \d+\.\d+/'
  artifacts:
    paths:
      - public
#    expire_in: 30 days
  only:
    - dev
