image: docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:16.04
stages:
  - test
  - triggers

test:
  stage: test
  script:
    - apt-get install curl -y --force-yes
    - curl -sL https://deb.nodesource.com/setup_8.x > nodejs-repo
    - chmod +x nodejs-repo
    - ./nodejs-repo
    - rm nodejs-repo
    - apt-get install -y --force-yes nodejs git
    - npm install -g yarn
    - make deps
    - make test || (cat xunit.xml ; echo "fail"  && exit 1)
  variables:
    PATCH: $CI_BUILD_ID

trigger-dev:
  stage: triggers
  script:
   - curl -X POST -F token=$GUI_TOKEN -F ref=dev https://git.oxfordnanolabs.local/api/v3/projects/224/trigger/builds # desktop agent dev
   - curl -X POST -F token=$CLI_TOKEN -F ref=dev https://git.oxfordnanolabs.local/api/v3/projects/225/trigger/builds # cli agent dev
# by default agent & cli both pull api#master so strictly, triggering dev builds from api#dev is meaningless...
#   - curl -X POST -F token=$GUI_TOKEN -F ref=master https://git.oxfordnanolabs.local/api/v3/projects/224/trigger/builds # desktop agent master
#   - curl -X POST -F token=$CLI_TOKEN -F ref=master https://git.oxfordnanolabs.local/api/v3/projects/225/trigger/builds # cli agent master
  only:
   - dev

trigger-testing:
  stage: triggers
  script:
   - curl -X POST -F token=$GUI_TOKEN -F ref=master https://git.oxfordnanolabs.local/api/v3/projects/224/trigger/builds # desktop agent master
   - curl -X POST -F token=$CLI_TOKEN -F ref=master https://git.oxfordnanolabs.local/api/v3/projects/225/trigger/builds # cli agent master
  only:
   - master
