image: docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:16.04
stages:
  - test
  - triggers
  - publish

.common: &common |
   sed -i 's|deb http://deb-repo.oxfordnanolabs.local/apt|#deb http://deb-repo.oxfordnanolabs.local/apt|g' /etc/apt/sources.list /etc/apt/sources.list.d/*.list || true
   apt-get clean
   apt-get update
   apt-get install -y curl git wget lsb-release gnupg build-essential openssl
   wget -O- http://deb-repo.oxfordnanolabs.local/apt/roger.pettett@nanoporetech.com.key | apt-key add -
   echo "deb http://deb-repo.oxfordnanolabs.local/apt $(lsb_release -cs) non-free" > /etc/apt/sources.list.d/deb-repo.list
   apt-get update

.deps: &deps |
   curl -sL https://deb.nodesource.com/setup_8.x > nodejs-repo
   chmod +x nodejs-repo
   ./nodejs-repo
   rm nodejs-repo
   make deps

test:
  stage: test
  script:
    - *common
    - *deps
    - make cover
  variables:
    PATCH: $CI_BUILD_ID

release:
  stage: publish
  script:
    - *deps
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    - npm publish
  only:
    - /^release-\d+\.\d+(?:.\d+)?(?:-\S+)?$/ # use regexp
  only:
    - tags

pages:
  stage: triggers
  allow_failure: true
  script:
    - *common
    - *deps
    - mkdir -p public
    - (make cover | tee coverage.txt) && mv coverage/* public/
    - (echo -n "Coverage "; grep "All files" coverage.txt | awk '{print $6}')
    - rm coverage.txt
  coverage: '/Coverage \d+\.\d+/'
  artifacts:
    paths:
      - public
#    expire_in: 30 days
  only:
    - dev

trigger-dev:
  stage: triggers
  script:
   - curl -X POST -F token=$GUI_TOKEN -F ref=dev https://git.oxfordnanolabs.local/api/v3/projects/224/trigger/builds # desktop agent dev
   - curl -X POST -F token=$CLI_TOKEN -F ref=dev https://git.oxfordnanolabs.local/api/v3/projects/225/trigger/builds # cli agent dev
# by default agent & cli both pull api#master so strictly, triggering dev builds from api#dev is meaningless...
#   - curl -X POST -F token=$GUI_TOKEN -F ref=master https://git.oxfordnanolabs.local/api/v3/projects/224/trigger/builds # desktop agent master
#   - curl -X POST -F token=$CLI_TOKEN -F ref=master https://git.oxfordnanolabs.local/api/v3/projects/225/trigger/builds # cli agent master
  only:
   - dev

trigger-testing:
  stage: triggers
  script:
   - curl -X POST -F token=$GUI_TOKEN -F ref=master https://git.oxfordnanolabs.local/api/v3/projects/224/trigger/builds # desktop agent master
   - curl -X POST -F token=$CLI_TOKEN -F ref=master https://git.oxfordnanolabs.local/api/v3/projects/225/trigger/builds # cli agent master
  only:
   - master
