image: docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:14.04

stages:
  - package

build:
  stage: package
  script:
    - apt-get install curl -y --force-yes
    - curl -sL https://deb.nodesource.com/setup_6.x > nodejs-repo
    - chmod +x nodejs-repo
    - ./nodejs-repo
    - rm nodejs-repo
    - apt-get install -y --force-yes nodejs
    - make deps
    - make test
  variables:
    PATCH: $CI_BUILD_ID
