image: docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:14.04
stages:
  - test
test:
  stage: test
  script:
    - apt-get install curl -y --force-yes
    - curl -sL https://deb.nodesource.com/setup_6.x > nodejs-repo
    - chmod +x nodejs-repo
    - ./nodejs-repo
    - rm nodejs-repo
    - apt-get install -y --force-yes nodejs git
    - make deps
    - make test || cat xunit.xml || (echo "fail"  && exit 1)
  variables:
    PATCH: $CI_BUILD_ID